apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cloudsweep.fullname" . }}-config
  namespace: {{ .Values.namespace }}
data:
  regions: {{ .Values.regions | quote }}
  cpu-idle-threshold: {{ .Values.cpuIdleThreshold | quote }}
  age-days-threshold: {{ .Values.ageDaysThreshold | quote }}
