apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cloudsweep.fullname" . }}-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  postgres-password: {{ .Values.postgres.password | b64enc | quote }}
  database-url: {{ printf "postgresql://%s:%s@%s:%v/%s" .Values.postgres.username .Values.postgres.password (include "postgres.host" .) .Values.postgres.port .Values.postgres.database | b64enc | quote }}
  {{- if .Values.slack.webhook }}
  slack-webhook: {{ .Values.slack.webhook | b64enc | quote }}
  {{- end }}
  {{- if .Values.aws.accessKeyId }}
  access-key-id: {{ .Values.aws.accessKeyId | b64enc | quote }}
  {{- end }}
  {{- if .Values.aws.secretAccessKey }}
  secret-access-key: {{ .Values.aws.secretAccessKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.aws.sessionToken }}
  session-token: {{ .Values.aws.sessionToken | b64enc | quote }}
  {{- end }}
