{{- if and .Values.monitoring.serviceMonitor.enabled (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1") }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "cloudsweep.fullname" . }}-pushgateway
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "cloudsweep.labels" . | nindent 4 }}
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: pushgateway
  namespaceSelector:
    matchNames:
      - {{ .Values.namespace }}
  endpoints:
    - port: metrics
      interval: {{ .Values.monitoring.serviceMonitor.interval }}
      honorLabels: true
{{- end }}
